# Generated by Django 3.0.8 on 2020-07-01 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evictions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('defendant', models.TextField()),
                ('defendant_zipcode', models.IntegerField()),
                ('disposition_date', models.DateField()),
                ('file_date', models.DateField()),
                ('judgment_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('last_event_date', models.DateField()),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=12)),
                ('plaintiff', models.TextField()),
                ('plaintiff_zipcode', models.IntegerField()),
                ('status', models.TextField()),
                ('ujs_id', models.IntegerField()),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evictions.Court')),
            ],
        ),
    ]
