# Generated by Django 3.0.8 on 2020-07-06 16:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('evictions', '0003_auto_20200701_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='last_scraped_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
